server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: batch_service_db
      username: gad-dev
      password: 123456789
      auto-index-creation: true

  datasource:
    url: jdbc:postgresql://localhost:5432/batch_metadata_db
    username: gad-dev
    password: 123456789
    driver-class-name: org.postgresql.Driver

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}